### ISSUE TITLE
Support Identity v3

### ISSUE THREAD

**Issue by stenstad** [mrkamel/swift_client#1]
Hi!

Since the release of Openstack Havana the preferred version of Identity to use is v3. Some cloud providers have now migrated to only supporting v3 for token generation to get support for domains.

Currently the Swift Client does not work with providers that require support for Identity v3.

Would it be possible to add support for Identity v3 in this project as well?

**Comment by mrkamel** [comment]
sure, it's not in because i didn't need it yet, but i'll check this asap.

**Comment by stenstad** [comment]
Do you need somewhere to test it? If you create an account at Zetta.IO I can magically enable it for Object Storage.

**Comment by mrkamel** [comment]
that would be nice. unfortunately, i don't receive the signup sms

**Comment by mrkamel** [comment]
release 0.1.2 now supports v3
