### ISSUE TITLE
How do you set a timeout and other HTTParty parameters locally?

### ISSUE THREAD

**Issue by raimondasv** [mrkamel/swift_client#5]
The gem uses global HTTParty objects to do the HTTP lifting, maybe it is worth providing HTTParty instance via options? I could customize HTTParty::Basement object, but this changes global options of HTTParty gem.

**Comment by mrkamel** [comment]
yep, i guess we can add a feature to pass through another options hash, this time to httparty. This will tie it even more to HTTParty, but as we already return the raw HTTParty responses to the end user, this shouldn't be much of an issue.

**Comment by mrkamel** [comment]
I merged it into master. Maybe you could check that out ...

**Comment by raimondasv** [comment]
@mrkamel thank you very much, following code works
```
swift_client.put_container('test', logger: Logger.new($stdout), log_level: :debug)
```
At first, I thought it would be easier to have options on instance level, but having it on method is more flexible, as one might want different timeouts for reading and writing.

Thank you for an update! Now if you only could publish the gem... :), it would be great!

**Comment by mrkamel** [comment]
released
